## Tensor的排序
比较重要的是排序函数**sort()**，选择沿着指定维度进行排序，返回排序后的Tensor及对应的索引位置。

In [1]:
import torch

In [2]:
a = torch.randn(3, 3)
a

tensor([[-0.8844, -0.1285,  1.0736],
        [-0.4333, -0.1141, -0.2593],
        [ 0.3682, -0.2139, -0.1907]])

In [3]:
#sort(dim, True/False)[sorted/indices]，()里的数字表示排序维度，[]里的数字表示排序结果的输出形式
#[0]表示输出排序后的Tensor，[1]表示输出排序后Tensor所在排序维度的原下标
#按照第0维即按行排序，每一列进行比较，True代表降序，False代表升序
a.sort(0, True)[0]

tensor([[ 0.3682, -0.1141,  1.0736],
        [-0.4333, -0.1285, -0.1907],
        [-0.8844, -0.2139, -0.2593]])

In [4]:
#按照第1维即按列排序，每一行进行比较，True代表降序，False代表升序
a.sort(1, False)[1]

tensor([[0, 1, 2],
        [0, 2, 1],
        [1, 2, 0]])

## Tensor取极值
**max()与min()**函数则是沿着指定维度选择最大与最小元素，返回该元素及对应的索引位置。

In [5]:
#按照第0维即按行选取最大值
a.max(0)

torch.return_types.max(
values=tensor([ 0.3682, -0.1141,  1.0736]),
indices=tensor([2, 1, 0]))

In [6]:
#按照第1维即按列选取最小值
a.min(1)

torch.return_types.min(
values=tensor([-0.8844, -0.4333, -0.2139]),
indices=tensor([0, 0, 1]))

### 对于Tensor的单元素数学运算，如abs()、sqrt()、log()、pow()和三角函数等，都是逐元素操作（element-wise），输出的Tensor形状与原始Tensor形状一致。

### 对于类似求和、求均值、求方差、求距离等需要多个元素完成的操作，往往需要沿着某个维度进行计算，在Tensor中属于归并操作，输出形状小于输入形状。